sonar.projectKey=AisD-1998_wealth_wise
sonar.organization=aisd-1998

# Sources
sonar.sources=lib

# Exclude generated and build files
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,build/**,.dart_tool/**,windows/runner/**,lib/firebase_options.dart

# Source encoding
sonar.sourceEncoding=UTF-8
