sonar.projectKey=aisd-1998_wealth_wise
sonar.organization=aisd-1998

# Sources
sonar.sources=lib
sonar.tests=test

# Exclude generated and build files
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,build/**,.dart_tool/**
