// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4dZWAjMu1Rz4hj2znVSUuMTc_Zz8jV8',
    appId: '1:1098925595954:web:2f5e3b0f4e1c83bfcc94b2b',
    messagingSenderId: '1098925595954',
    projectId: 'wealthwise-f96a5',
    authDomain: 'wealthwise-f96a5.firebaseapp.com',
    storageBucket: 'wealthwise-f96a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfB-f6-73O2VG2UlxEAaTzOtERbhr1yvQ',
    appId: '1:1098925595954:android:21c9b4efe1c83bfcc94b2b',
    messagingSenderId: '1098925595954',
    projectId: 'wealthwise-f96a5',
    storageBucket: 'wealthwise-f96a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7k2JUEx2rJ05XP8YdRu2y5IWI-4Dp1xo',
    appId: '1:1098925595954:ios:a7c9b4efe1c83bfcc94b2b',
    messagingSenderId: '1098925595954',
    projectId: 'wealthwise-f96a5',
    storageBucket: 'wealthwise-f96a5.firebasestorage.app',
    iosBundleId: 'com.example.wealthWise',
  );
}
