// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform is not supported yet - please configure Firebase manually',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platform is not supported yet - please configure Firebase manually',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS platform is not supported yet - please configure Firebase manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows platform is not supported yet - please configure Firebase manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux platform is not supported yet - please configure Firebase manually',
        );
      default:
        throw UnsupportedError(
          'Unknown platform $defaultTargetPlatform - please configure Firebase manually',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfB-f6-73O2VG2UlxEAaTzOtERbhr1yvQ',
    appId: '1:1098925595954:android:21c9b4efe1c83bfcc94b2b',
    messagingSenderId: '1098925595954',
    projectId: 'wealthwise-f96a5',
    storageBucket: 'wealthwise-f96a5.firebasestorage.app',
  );
}
